VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISummaryUpdater"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Sub Update(engine As RuleEngine, sheet As Worksheet)
End Sub

Function GetVersion() As String
End Function

Function ClearSheet(ws As Worksheet)
End Function
Function FitAllColumns(ws As Worksheet)
End Function
