VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "RuleColumn"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Public Name As String
'Public Operator As String
Public Operator As Operators
Public Value As String
'Public ColType As ColumnType
Public Link As String
Public ReturnValue As String
Public ReturnID As String
Public PrintAble As Boolean




